name = "GithubMarkdown"
uuid = "ecb7cac2-dae3-4a6f-a5f6-8274be99c6cb"
authors = ["Sebastian Pfitzner"]
version = "0.1.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"
BinaryProvider = "0.3, 0.4, 0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
